version: '3.5'

services:
  app:
    build:
      context: .
      shm_size: '500mb'
    container_name: shortlink-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3100
      - DB_ENDPOINT=mongodb://shortlink:shortlink@mongo:27017/shortlink
    ports:
      - 3100:3100
    networks:
      - services-network
