name: Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint
      env:
        CI: true
    - name: Unit Test
      run: npm run test:unit
      env:
        CI: true
    - name: Acceptance Test
      run: npm run test:acceptance
      env:
        CI: true
    - name: Visual Regression
      run: npm run test:visual
      env:
        CI: true
