name: Tests

on: [push]

jobs:
  static:
    name: Static Tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test:unit
      - name: Acceptance Test
        run: yarn test:acceptance
