name: Visual Regression

on: [push]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag shortlink --shm-size 512M

  visual:
    name: Visual Regression
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mongo:latest
        container_name: shortlink-mongo
        restart: always
        environment:
          - MONGO_INITDB_DATABASE=shortlink
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
          - ./config/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
          - mongo-data:/data/db
      app:
        image: shortlink:latest
        container_name: shortlink-app
        restart: always
        environment:
          - NODE_ENV=production
          - APP_PORT=3000
          - DB_ENDPOINT=mongodb://shortlink:shortlink@mongo:27017/shortlink
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: yarn install
      - name: Visual Regression
        run: yarn test:visual
